import express from 'express';
const router=express.Router();
import { GetUser,GetByIdUser,CreateUser ,UpdateUser,DeleteUser} from '../controller/controller.js';
router.use(express.json());
router.post('/Signin',CreateUser);
router.get('/Signin',GetUser);
router.get('/Signin/:id',GetByIdUser);
router.put('/Signin/:id',UpdateUser);
router.delete('/Signin/:id',DeleteUser);
export default router;