import express from 'express';
const router=express.Router();
import GetApi from '../controller/Get.js';
import PostApi from '../controller/Post.js';
import GetByIdApi from '../controller/GetById.js';
import UpdateApi from '../controller/Update.js';
import DelApi from '../controller/Del.js';
router.use(express.json());
router.post('/',PostApi);
router.get('/',GetApi);
router.get('/:id',GetByIdApi);
router.put('/:id', UpdateApi);
router.delete('/:id', DelApi);
export default router;